services:
  _defaults:
    public: true

  Apisearch\Listener\ProductUpdateListener:
    class: Apisearch\Listener\ProductUpdateListener
    tags:
      - { name: kernel.event_listener, event: kernel.response, method: pushToApisearch }
